-- MySQL Script generated by MySQL Workbench
-- Seg 18 Abr 2016 10:12:11 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projeto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `projeto` ;

-- -----------------------------------------------------
-- Table `projeto`.`escola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`escola` (
  `id_escola` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_escola`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`cidade` (
  `idcidade` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(100) NOT NULL COMMENT '',
  `escola_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idcidade`, `escola_id`)  COMMENT '',
  INDEX `fk_cidade_escola1_idx` (`escola_id` ASC)  COMMENT '',
  CONSTRAINT `fk_cidade_escola1`
    FOREIGN KEY (`escola_id`)
    REFERENCES `projeto`.`escola` (`id_escola`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`aluno` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(100) NOT NULL COMMENT '',
  `nasc` DATE NOT NULL COMMENT '',
  `cidade_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_aluno`, `cidade_id`)  COMMENT '',
  INDEX `fk_aluno_cidade1_idx` (`cidade_id` ASC)  COMMENT '',
  CONSTRAINT `fk_aluno_cidade1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `projeto`.`cidade` (`idcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`login` (
  `id_login` INT NOT NULL AUTO_INCREMENT COMMENT '						',
  `user` VARCHAR(100) NOT NULL COMMENT '',
  `pass` VARCHAR(100) NOT NULL COMMENT '',
  `aluno_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_login`, `aluno_id`)  COMMENT '',
  INDEX `fk_login_aluno_idx` (`aluno_id` ASC)  COMMENT '',
  CONSTRAINT `fk_login_aluno`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `projeto`.`aluno` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(100) NOT NULL COMMENT '',
  `duracao` INT NOT NULL COMMENT '',
  `nivel` VARCHAR(15) NOT NULL COMMENT '',
  PRIMARY KEY (`id_curso`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto`.`escola_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`escola_curso` (
  `escola_id` INT NOT NULL COMMENT '',
  `curso_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`escola_id`, `curso_id`)  COMMENT '',
  INDEX `fk_escola_has_curso_curso1_idx` (`curso_id` ASC)  COMMENT '',
  INDEX `fk_escola_has_curso_escola1_idx` (`escola_id` ASC)  COMMENT '',
  CONSTRAINT `fk_escola_has_curso_escola1`
    FOREIGN KEY (`escola_id`)
    REFERENCES `projeto`.`escola` (`id_escola`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escola_has_curso_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `projeto`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto`.`aluno_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`aluno_curso` (
  `curso_id` INT NOT NULL COMMENT '',
  `aluno_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`curso_id`, `aluno_id`)  COMMENT '',
  INDEX `fk_curso_has_aluno_aluno1_idx` (`aluno_id` ASC)  COMMENT '',
  INDEX `fk_curso_has_aluno_curso1_idx` (`curso_id` ASC)  COMMENT '',
  CONSTRAINT `fk_curso_has_aluno_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `projeto`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso_has_aluno_aluno1`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `projeto`.`aluno` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto`.`semestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`semestre` (
  `id_semestre` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `semestre` INT NOT NULL COMMENT '',
  `curso_id` INT NOT NULL COMMENT '',
  `aluno_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_semestre`, `curso_id`, `aluno_id`)  COMMENT '',
  INDEX `fk_semestre_aluno_curso1_idx` (`curso_id` ASC, `aluno_id` ASC)  COMMENT '',
  CONSTRAINT `fk_semestre_aluno_curso1`
    FOREIGN KEY (`curso_id` , `aluno_id`)
    REFERENCES `projeto`.`aluno_curso` (`curso_id` , `aluno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`materia` (
  `id_materia` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(100) NOT NULL COMMENT '',
  `prof` VARCHAR(100) NULL COMMENT '',
  `semestre_id_semestre` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_materia`, `semestre_id_semestre`)  COMMENT '',
  INDEX `fk_materia_semestre1_idx` (`semestre_id_semestre` ASC)  COMMENT '',
  CONSTRAINT `fk_materia_semestre1`
    FOREIGN KEY (`semestre_id_semestre`)
    REFERENCES `projeto`.`semestre` (`id_semestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto`.`atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`atividade` (
  `id_atividade` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(100) NOT NULL COMMENT '',
  `descricao` TEXT NULL COMMENT '',
  `valor` VARCHAR(3) NULL COMMENT '',
  `data` DATE NULL COMMENT '',
  `materia_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_atividade`, `materia_id`)  COMMENT '',
  INDEX `fk_atividade_materia1_idx` (`materia_id` ASC)  COMMENT '',
  CONSTRAINT `fk_atividade_materia1`
    FOREIGN KEY (`materia_id`)
    REFERENCES `projeto`.`materia` (`id_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto`.`prova`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`prova` (
  `id_prova` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `data` DATE NOT NULL COMMENT '',
  `materia_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_prova`, `materia_id`)  COMMENT '',
  INDEX `fk_prova_materia1_idx` (`materia_id` ASC)  COMMENT '',
  CONSTRAINT `fk_prova_materia1`
    FOREIGN KEY (`materia_id`)
    REFERENCES `projeto`.`materia` (`id_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`material` (
  `id_material` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(100) NULL COMMENT '',
  `link` VARCHAR(200) NULL COMMENT '',
  `materia_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_material`, `materia_id`)  COMMENT '',
  INDEX `fk_material_materia1_idx` (`materia_id` ASC)  COMMENT '',
  CONSTRAINT `fk_material_materia1`
    FOREIGN KEY (`materia_id`)
    REFERENCES `projeto`.`materia` (`id_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
